name: edgefs
version: '2020.05.19'
summary: Snap package of EdgeFS
description: |
  University of Groningen - Software Engineering project.
  Package: EdgeFS Multi-Cloud Distributed Storage System.

base: core18
grade: devel
confinement: strict

apps:
  edgefs:
    command: opt/nedge/sbin/edgefs-start.sh

parts:
  edgefs:
    plugin: dump
    source: edgefs
    stage-packages:
      - libssl1.0.0
      - iputils-ping
      - iproute2
      - libnss3
      - libsnmp30
      - udev
      - bsdmainutils
      - libcgroup1
      - libcurl4
      - nvi
      - curl
      - gdisk
      - bcache-tools
      - parted
      - openssl
      - netbase
      - rpcbind
      - gdb
      - libaio1
      - libnuma1
      - nvme-cli
      - krb5-user
      - libatm1
